version: "3.9"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: money-api  
      POSTGRES_PASSWORD: root
      POSTGRES_DB: money-api
    ports:
     - 5432:5432
    volumes:
    - ./create.sql:/docker-entrypoint-initdb.d/create.sql 

  adminer:
    image: adminer
    environment:
      ADMINER_DESIGN: dracula
    ports:
     - 3333:8080